[package]
name = "lib-transport"
version.workspace = true
edition = "2021"

[lints]
workspace = true

[dependencies]
lib-asyncapi = { path = "../lib-asyncapi" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, optional = true }
url.workspace = true

[features]
rt = ["tokio"]
