<script lang="ts" module>
  import type { CodecInfo, ControlMeta, ProbedDevice, StreamInfo, StreamManifest, StreamMetrics } from '$lib/ts-bindings/http/client';
  import type { StreamControlSocket } from '$lib/api/streamControls';
  import type { connectStreamUpdates } from '$lib/api/streamUpdates';

  export function createCameraStreamState() {
    const state = $state({
      CONTROL_APPLY_DEBOUNCE_MS: 150,
      STREAM_PRESET_DEBOUNCE_MS: 300,
      loading: true,
      refreshing: false,
      stopping: false,
      error: null as string | null,
      stream: null as StreamInfo | null,
      manifestState: null as StreamManifest | null,
      streamMetrics: null as StreamMetrics | null,
      controls: [] as ControlMeta[],
      controlState: {} as Record<number, number | boolean | null>,
      controlAppliedState: {} as Record<number, number | boolean | null>,
      controlBusy: {} as Record<number, boolean>,
      controlSocket: null as StreamControlSocket | null,
      controlSocketStreamId: null as string | null,
      streamUpdatesSocket: null as ReturnType<typeof connectStreamUpdates> | null,
      streamUpdatesSocketStreamId: null as string | null,
      activeTab: 'stream' as 'stream' | 'media' | 'controls' | 'pipelines' | 'pose' | 'calibration',
      controlsQuery: '',
      selectedModeKey: null as string | null,
      selectedFormat: '',
      selectedResolution: '',
      selectedInterval: '',
      devices: [] as ProbedDevice[],
      codecs: [] as CodecInfo[],
      encoders: [] as CodecInfo[],
      decoders: [] as CodecInfo[],
      selectedDeviceIndex: 0,
      selectedBackendIndex: 0,
      selectedIntervalIdx: 0,
      libcameraTargetFps: null as number | null,
      netcamTargetFps: null as number | null,
      encoderImpl: null as string | null,
      decoderImpl: null as string | null,
      encoderEnabled: true,
      decoderEnabled: true,
      encoderSelectionTouched: false,
      decoderSelectionTouched: false,
      hostBuffer: 8,
      cameraAlias: '',
      decoderFpsLimit: null as number | null,
      decoderRotationDegrees: 0 as number | null,
      decoderMirrorHorizontal: false,
      encoderFpsLimit: null as number | null,
      encoderSettingsOpen: false,
      encoderSettings: {
        bitrate: null as number | null,
        gop: null as number | null,
        threadCount: null as number | null,
        outWidth: null as number | null,
        outHeight: null as number | null,
      },
      shadowRecorderEnabled: false,
      streamCrop: [-1, 1, -1, 1] as [number, number, number, number],
      streamCropGuidesEnabled: true,
      streamCropApplying: false,
      streamCropError: null as string | null,
      streamCropWarning: null as string | null,
      streamCrosshair: [0, 0] as [number, number],
      streamCrosshairEnabled: true,
      streamCrosshairGuidesEnabled: true,
      streamCrosshairApplying: false,
      streamCrosshairError: null as string | null,
      streamCrosshairWarning: null as string | null,
      streamOrderingMode: 'none',
      streamOrderingApplying: false,
      streamOrderingError: null as string | null,
      streamOrderingWarning: null as string | null,
      fileBackendFps: null as number | null,
      fileBackendLoop: true,
      fileBackendPathsText: '',
      applying: false,
      pendingStreamPresetApply: false,
      pendingStreamPresetSilent: true,
      controlApplyTimers: new Map<number, number>(),
      controlApplySeqById: new Map<number, number>(),
      streamPresetApplyTimer: null as number | null
    });

    return state;
  }
</script>
