[units."helios-engine.socket"]
enabled = true
src = "assets/services/helios-engine/helios-engine.socket"
unit = "helios-engine.socket"
targets = ["sockets"]

[units."helios-engine"]
enabled = true
src = "assets/services/helios-engine/helios-engine.service"
targets = ["multi-user"]
env_set = "helios-engine"
env_file = "/etc/default/helios-engine"
