pub mod calibration_solve;
pub mod console;
pub mod device;
pub mod error;
pub mod error_history;
pub mod health;
pub(crate) mod identity_tokens;
pub mod integrations;
pub(crate) mod json_store;
pub mod localization;
pub mod media;
pub mod nt4;
pub mod ota;
pub(crate) mod ota_storage;
pub mod peers;
pub mod peripherals;
pub(crate) mod persisted_files;
pub mod pipelines;
pub mod plugins;
pub(crate) mod reqwest_client;
pub(crate) mod revision;
pub mod startup;
pub mod storage;
pub mod streams;
pub mod streams_persist;
pub(crate) mod upload_integrity;
pub mod validation;

use axum::Router;
use axum::routing::{get, post};
use std::sync::Arc;
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        health::root_status,
        health::health,
        streams::list_streams,
        streams::start_stream,
        streams::validate_stream,
        streams::stream_capabilities_handler,
        streams::delete_stream,
        streams::get_controls,
        streams::set_control,
        streams::get_metrics,
        streams::stream_format,
        streams::preview_stream,
        streams::frame_jpeg,
        streams::snapshot::capture_snapshot,
        streams::snapshot::set_crop,
        streams::bench_formats,
        streams::set_pipeline_graph,
        streams::set_pipeline_layout,
        streams::set_pipeline_output,
        streams::smoke_pipeline_graph,
        streams::list_pipeline_outputs,
        streams::get_pipeline_output_sample,
        pipelines::list_templates,
        pipelines::fetch_template,
        streams::calibration::board_png,
        streams::calibration::board_pdf,
        streams::recording::start_recording,
        streams::recording::stop_recording,
        calibration_solve::solve_calibration,
        streams::calibration::apply_calibration,
        streams::calibration::save_calibration,
        streams::get_stream,
        streams::list_backends,
        streams::list_codecs,
        streams::update_stream_pose,
        streams::clear_stream_pose,
        device::identity::hostname,
        device::identity::set_hostname,
        device::network::network,
        device::network::set_network,
        device::network::team,
        device::network::set_team,
        device::nt4::get_nt4_settings,
        device::nt4::set_nt4_settings,
        device::usb_power::get_usb_power_settings,
        device::usb_power::set_usb_power_settings,
        device::logs::logs,
        device::logs::sources,
        device::logs::download,
        device::ide::ide_info,
        device::ide::ide_projects,
        device::ide::create_ide_project,
        device::imu::i2c,
        device::imu::imu_status,
        device::imu::update_imu,
        device::lighting::lighting_command,
        device::lighting::lighting_state,
        device::lighting::lighting_config,
        device::lighting::update_lighting_config,
        device::lighting::reset_lighting_config,
        device::lighting::list_lighting_templates,
        device::lighting::fetch_lighting_template,
        device::lighting::list_lighting_animations,
        device::lighting::save_lighting_animation,
        device::lighting::delete_lighting_animation,
        device::power::power_status,
        device::logs::console,
        device::metrics::metrics,
        device::resource_guard::status,
        device::resource_guard::restore,
        device::bootloader::status,
        device::bootloader::update,
        device::snapshots::list_device_snapshots,
        device::snapshots::capture_device_snapshot,
        device::snapshots::delete_device_snapshot,
        device::snapshots::download_device_snapshot,
        device::os_release::os_release,
        device::restart::restart,
        device::ipa::ipa_status,
        error_history::list_history,
        error_history::export_history,
        error_history::clear_history,
        device::ipa::download,
        device::ipa::apply_ccm,
        device::ipa::solve_ccm,
        device::ipa::chart_png,
        device::ipa::chart_pdf,
        device::rig::get_camera_layout,
        device::rig::update_robot_dimensions,
        device::rig::update_camera_pose,
        device::rig::clear_camera_pose,
        peripherals::list_peripherals,
        peripherals::list_cameras,
        media::list_media,
        media::upload_media,
        media::fetch_media,
        media::fetch_media_imu,
        media::attach_media_imu,
        media::delete_media_imu,
        media::delete_media,
        media::update_metadata,
        media::fetch_label,
        media::attach_label,
        media::apply_image_edits,
        console::list_sessions,
        console::create_session,
        console::delete_session,
        pipelines::upload_graph,
        pipelines::update_graph,
        pipelines::list_graphs,
        pipelines::fetch_graph,
        pipelines::delete_graph,
        pipelines::list_registry,
        pipelines::validate_graph,
        peers::list_peers,
        peers::register_peer,
        peers::discover_peers,
        peers::probe_peer,
        peers::photonvision_discover_streams,
        peers::remove_peer,
        nt4::list_topics,
        nt4::read_value,
        peripherals::list_i2c,
        peripherals::list_usb,
        peripherals::fan_status,
        peripherals::led_status,
        ota::upload_update,
        ota::stage_update,
        ota::apply_update,
        ota::cancel_update,
        ota::updater_state,
        plugins::list_plugins,
        plugins::upload_plugin,
        plugins::install_plugin,
        plugins::download_plugin,
        plugins::download_disabled,
        plugins::download_upload,
        plugins::delete_plugin,
        plugins::disable_plugin,
        plugins::enable_plugin,
        localization::sources::list_sources,
        localization::validate_localization,
        localization::localization_capabilities_handler,
        localization::config::get_config,
        localization::config::update_config,
        localization::config::export_profiles,
        localization::config::import_profiles,
        localization::external::list_external_sources,
        localization::external::upsert_external_source,
        localization::external::delete_external_source,
        localization::external::update_external_sample,
        localization::external::sample_external_output,
        localization::solve::solve,
        localization::sources::sample_output,
        localization::sources::sample_peer_output,
        localization::maps::list_maps,
        localization::maps::fetch_map,
        localization::maps::upload_limelight_fmap,
    ),
    components(
        schemas(
            helios_engine::ipc::StreamManifest,
            helios_engine::stream::StreamMetrics,
            streams::bench::BenchFormatsRequest,
            streams::bench::BenchFormatsResponse,
            streams::validation::StreamValidateResponse,
            streams::validation::StreamCapabilitiesResponse,
            streams::validation::StreamValidationDefaults,
            streams::validation::StreamValidationConstraints,
            health::RuntimeStreamsPayload,
            health::RootStatusPayload,
            streams::sensor_bench::StartSensorBenchmarkRequest,
            streams::sensor_bench::SensorBenchmarkStarted,
            streams::sensor_bench::SensorBenchmarkProgress,
            streams::sensor_bench::SensorBenchmarkStatus,
            streams::sensor_bench::SensorBenchmarkSummary,
            streams::sensor_bench::CpuSample,
            streams::sensor_bench::BenchCodecStatCpu,
            streams::sensor_bench::SensorBenchModeResult,
            streams::sensor_bench::SensorBenchmarkResult,
            streams::sensor_bench::SensorBenchmarkListItem,
            streams::sensor_bench::SensorBenchmarkListResponse,
            device::DeviceMetrics,
            device::DiskMetrics,
            device::CpuCoreMetrics,
            device::TempReading,
            crate::resource_guard::ResourceGuardStatus,
            crate::resource_guard::ResourceGuardAction,
            crate::resource_guard::ResourceGuardActionKind,
            crate::resource_guard::ResourceGuardDegradedStream,
            crate::resource_guard::ResourceGuardStage,
            device::bootloader::BootloaderStatus,
            device::bootloader::BootloaderUpdateRequest,
            device::bootloader::BootloaderUpdateResponse,
            device::os_release::OsReleaseInfo,
            lib_sensors::dto::ImuAxesPayload,
            lib_sensors::dto::ImuOrientationPayload,
            lib_sensors::dto::ImuQuaternionPayload,
            lib_sensors::dto::ImuSourcesPayload,
            lib_sensors::dto::ImuOptionsPayload,
            lib_sensors::dto::ImuStatusPayload,
            lib_sensors::dto::ImuUpdateRequest,
            device::lighting::LightingCommandRequest,
            device::lighting::LightingRuntimeStatePayload,
            device::lighting::LightingColorPayload,
            device::lighting::LightingAnimationPayload,
            device::lighting::LightingConfigRequest,
            device::lighting::LightingAnimationSaveRequest,
            device::lighting::LightingAnimationTemplateSummary,
            device::lighting::LightingAnimationTemplateDocument,
            device::lighting::LightingAnimationEntryResponse,
            device::lighting::LightingAnimationListResponse,
            lib_sensors::led_config::LedConfig,
            device::usb_power::UsbPowerSettings,
            device::PowerSourcePayload,
            device::PowerStatusPayload,
            device::ide::IdeInfo,
            device::ide::IdeProjectEntry,
            device::ide::IdeProjectsResponse,
            device::ide::CreateIdeProjectRequest,
            device::ide::CreateIdeProjectResponse,
            device::restart::RestartRequest,
            device::restart::RestartTargetId,
            device::restart::DeviceOperationAckResponse,
            device::rig::CameraLayoutResponse,
            device::rig::CameraLayoutCameraResponse,
            device::rig::RobotDimensions,
            device::rig::RigPose,
            device::rig::PoseVector,
            device::rig::PoseRotation,
            device::rig::UpdateRobotDimensionsRequest,
            device::rig::UpdateCameraPoseRequest,
            media::MediaItem,
            pipelines::PipelineDocument,
            pipelines::PipelineSummary,
            pipelines::PipelineTemplateDocument,
            pipelines::PipelineTemplateSummary,
            pipelines::UploadGraphRequest,
            pipelines::PipelineError,
            pipelines::DaedalusRegistryNode,
            pipelines::DaedalusRegistryResponse,
            pipelines::DaedalusSyncGroup,
            pipelines::ValidateGraphRequest,
            pipelines::ValidateGraphResponse,
            pipelines::PlannerDiagnostic,
            pipelines::PlannerDiagnosticSpan,
            peers::PeerInfo,
            peers::PeerStatus,
            peers::PeerDiscoveryRequest,
            peers::PeerDiscoveryResponse,
            peers::PeerInventoryResponse,
            peers::PeerRegistrationResponse,
            peers::PeerRemovalResponse,
            peers::RegisterPeerRequest,
            peers::PeerProbeRequest,
            peers::PeerProbeResponse,
            peers::ProbeResult,
            peers::PhotonvisionDiscoverStreamsRequest,
            peers::PhotonvisionDiscoverStreamsResponse,
            peers::DiscoveredStream,
            peers::PeerError,
            peripherals::PeripheralInventory,
            peripherals::CameraDiscoveryResponse,
            peripherals::UsbPeripheral,
            peripherals::LightingStatus,
            peripherals::FanStatus,
            peripherals::ErrorBody,
            ota::UploadUpdateResponse,
            ota::UploadUpdateError,
            ota::StageUpdateRequest,
            ota::UpdateAckResponse,
            ota::ApplyUpdateRequest,
            ota::UpdateStateResponse,
            plugins::PluginFile,
            plugins::PluginListResponse,
            plugins::PluginUploadResponse,
            plugins::PluginInstallRequest,
            plugins::PluginInstallResponse,
            plugins::PluginToggleResponse,
            error::ErrorBody,
            validation::ValidationErrorBody,
            validation::ValidationIssue,
            validation::ValidationWarning,
            error_history::ErrorHistoryEntry,
            error_history::ErrorHistoryResponse,
            console::CreateConsoleSessionRequest,
            crate::console_sessions::ConsoleSessionSummaryPayload,
            crate::console_sessions::ConsoleSessionListPayload,
            streams::calibration::StreamCalibrationParams,
            calibration_solve::SolveCalibrationBoard,
            calibration_solve::SolveCalibrationRequest,
            calibration_solve::SolveCalibrationResponse,
            calibration_solve::SolveCalibrationDebugView,
            helios_engine::ipc::CalibrationSolveConfig,
            device::ipa::IpaFileInfo,
            device::ipa::IpaStatus,
            device::ipa::ApplyCcmRequest,
            device::ipa::SolveCcmRequest,
            device::ipa::SolveCcmResponse,
            device::ipa::ColorChart,
            device::fan::FanConfigRequest,
            device::snapshots::CaptureSnapshotRequest,
            device::snapshots::DeviceSnapshotResponse,
            device::snapshots::DeviceSnapshotsResponse,
            helios_engine::localization::types::LocalizationPipelineSource,
            helios_engine::localization::types::PipelineOutputSample,
            helios_engine::localization::config::LocalizationConfig,
            helios_engine::localization::config::LocalizationProfile,
            helios_engine::localization::config::LocalizationSourceConfig,
            helios_engine::localization::config::LocalizationSolverConfig,
            helios_engine::localization::config::LocalizationSolverMode,
            helios_engine::localization::config::LocalizationPoseSpace,
            helios_engine::localization::types::LocalizationPipelineStatus,
            helios_engine::localization::types::LocalizationSolveResponse,
            helios_engine::localization::types::LocalizationSolverResult,
            helios_engine::localization::types::LocalizationSolverOutputs,
            helios_engine::localization::types::LocalizationDetectionPose,
            helios_engine::localization::types::LocalizationSourcePose,
            helios_engine::localization::types::LocalizationSolverPose,
            helios_engine::localization::types::LocalizationPose,
            helios_engine::localization::types::LocalizationVector,
            helios_engine::localization::types::LocalizationRotation,
            helios_engine::localization::types::LocalizationQuaternion,
            helios_engine::localization::types::LocalizationSourceSampleStatus,
            helios_engine::localization::external::ExternalLocalizationSource,
            helios_engine::localization::external::ExternalLocalizationSourceUpsert,
            helios_engine::localization::external::ExternalLocalizationSampleRequest,
            helios_engine::localization::external::ExternalLocalizationSample,
            helios_engine::localization::maps::FieldMapSummary,
            helios_engine::localization::maps::FieldMapDocument,
            helios_engine::localization::maps::FieldMapMarker,
            helios_engine::localization::maps::FieldQuaternion,
            helios_engine::localization::maps::FieldMapSource,
            helios_engine::localization::maps::FieldMapTagBits,
            localization::validation::LocalizationValidateResponse,
            localization::validation::LocalizationCapabilitiesResponse,
            localization::validation::LocalizationValidationDefaults,
            localization::validation::LocalizationValidationConstraints,
            localization::config::LocalizationProfilesExportEnvelope,
            localization::config::LocalizationProfilesImportRequest,
            crate::nt4::limelight::LimelightAdapterRegistryStatus,
            crate::nt4::limelight::LimelightAdapterStatus,
            crate::nt4::limelight_types::LimelightAdapterId,
            crate::nt4::limelight_types::LimelightReadSnapshot,
            crate::nt4::limelight_types::LimelightControlState,
        )
    ),
    tags(
        (name = "EngineStreams", description = "Engine streaming control"),
        (name = "Device", description = "Device/system endpoints"),
        (name = "Peripherals", description = "Peripheral inventory"),
        (name = "Media", description = "Stored media assets"),
        (name = "Pipelines", description = "Pipeline graph storage and templates"),
        (name = "Localization", description = "Localization + tag feeds"),
        (name = "Peers", description = "Peer discovery and registration"),
        (name = "NT4", description = "NetworkTables (NT4) helpers"),
        (name = "OTA", description = "Over-the-air OS updates"),
        (name = "Console", description = "Console session management"),
        (name = "Plugins", description = "Daedalus plugin management"),
        (name = "Errors", description = "Error history and exports"),
        (name = "Calibration", description = "Camera calibration workflows"),
    )
)]
pub struct ApiDoc;

/// Top-level HTTP router; currently stubs only.
pub type AppState = Arc<crate::app_state::ApiAppState>;

pub fn router(state: AppState) -> Router {
    Router::new()
        .route("/", get(health::root_status))
        .route("/health", get(health::health))
        .route("/calibration/solve", post(calibration_solve::solve_calibration))
        .nest("/streams", streams::router())
        .nest("/peripherals", peripherals::router())
        .nest("/device", device::router())
        .nest("/console", console::router())
        .nest("/media", media::router())
        .nest("/ota", ota::router())
        .nest("/pipelines", pipelines::router())
        .nest("/plugins", plugins::router())
        .nest("/errors", error_history::router())
        .nest("/localization", localization::router())
        .nest("/peers", peers::router())
        .nest("/integrations/limelight", integrations::limelight::router())
        .nest("/nt4", nt4::router())
        .with_state(state)
}
