[Unit]
After=network.target helios-os-self-check.service
Wants=network.target helios-os-self-check.service

[Service]
RuntimeDirectory=sshd
RuntimeDirectoryMode=0755
ExecStartPre=
ExecStartPre=/usr/bin/install -d -m0755 /run/sshd
ExecStartPre=/usr/bin/ssh-keygen -A
