[package]
name = "helios-daedalus-led-plugin"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[features]
default = ["plugins"]
plugins = []

[dependencies]
daedalus = { workspace = true, features = ["ffi", "plugins", "gpu"] }
helios-peripherals = { path = "../../helios-peripherals", default-features = false, features = ["dto"] }
lib-ipc = { path = "../../libs/lib-ipc" }
lib-led-animations = { path = "../../libs/lib-led-animations" }
lib-runtime-policy = { path = "../../libs/lib-runtime-policy" }
paste = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
