[package]
name = "lib-led-animations"
version.workspace = true
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
lib-lighting = { path = "../lib-lighting" }
lib-schema-migration = { path = "../lib-schema-migration" }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
