// This file is generated by gaia/tools/runtime-policy/render_runtime_policy.py.
// Source: gaia/configs/env/runtime/runtime-policy-source.toml

use crate::{BoundedU64Policy, BoundedUsizePolicy, TokioRuntimePolicy};

pub const HELIOS_API_TOKIO_POLICY: TokioRuntimePolicy = TokioRuntimePolicy {
    worker_threads: BoundedUsizePolicy { env_var: "HELIOS_API_WORKER_THREADS", default: 2, min: 1, max: 8 },
    max_blocking_threads: BoundedUsizePolicy { env_var: "HELIOS_API_MAX_BLOCKING_THREADS", default: 4, min: 1, max: 32 },
    thread_stack_bytes: Some(BoundedUsizePolicy { env_var: "HELIOS_API_THREAD_STACK_BYTES", default: 1048576, min: 262144, max: 8388608 }),
    blocking_keep_alive_ms: Some(BoundedU64Policy { env_var: "HELIOS_API_BLOCKING_KEEP_ALIVE_MS", default: 500, min: 100, max: 60000 }),
};

pub const HELIOS_ENGINE_TOKIO_POLICY: TokioRuntimePolicy = TokioRuntimePolicy {
    worker_threads: BoundedUsizePolicy { env_var: "HELIOS_ENGINE_WORKER_THREADS", default: 4, min: 1, max: 4 },
    max_blocking_threads: BoundedUsizePolicy { env_var: "HELIOS_ENGINE_MAX_BLOCKING_THREADS", default: 4, min: 1, max: 16 },
    thread_stack_bytes: Some(BoundedUsizePolicy { env_var: "HELIOS_ENGINE_THREAD_STACK_BYTES", default: 2097152, min: 262144, max: 8388608 }),
    blocking_keep_alive_ms: Some(BoundedU64Policy { env_var: "HELIOS_ENGINE_BLOCKING_KEEP_ALIVE_MS", default: 3000, min: 250, max: 60000 }),
};

pub const HELIOS_PERIPHERALS_TOKIO_POLICY: TokioRuntimePolicy = TokioRuntimePolicy {
    worker_threads: BoundedUsizePolicy { env_var: "HELIOS_PERIPHERALS_WORKER_THREADS", default: 1, min: 1, max: 4 },
    max_blocking_threads: BoundedUsizePolicy { env_var: "HELIOS_PERIPHERALS_MAX_BLOCKING_THREADS", default: 1, min: 1, max: 16 },
    thread_stack_bytes: None,
    blocking_keep_alive_ms: None,
};
