[package]
name = "helios-daedalus-cv-plugin"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
daedalus = { workspace = true, features = ["ffi", "plugins", "gpu"] }
lib-cv = { path = "../../libs/lib-cv", default-features = false, features = ["engine", "plugins", "gpu", "aruco", "contour", "draw"] }
