[package]
name = "helios-usbctl"
version.workspace = true
edition = "2024"

[dependencies]
anyhow = "1.0"
base64 = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
libc = { workspace = true }

[lints]
workspace = true
