#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
import io
import pathlib
import subprocess
import sys
import tomllib


REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE_PATH = REPO_ROOT / "assets" / "layout" / "storage-layouts.toml"
OUTPUT_DIR = REPO_ROOT / "assets" / "generated" / "storage-layouts"


def slugify_layout_id(layout_id: str) -> str:
    return layout_id.replace("_", "-")


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def load_source() -> dict:
    with SOURCE_PATH.open("rb") as handle:
        data = tomllib.load(handle)
    layouts = data.get("layouts")
    if not isinstance(layouts, list) or not layouts:
        raise SystemExit(f"{SOURCE_PATH} does not contain any [[layouts]] entries")
    return data


def require_partition(layout: dict, role: str) -> dict:
    for partition in layout.get("partitions", []):
        if partition.get("role") == role:
            return partition
    raise SystemExit(f"layout {layout.get('layout_id')} is missing required role {role}")


def render_toml_value(value) -> str:
    if value is None:
        raise ValueError("cannot render None into TOML")
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    raise TypeError(f"unsupported TOML value {value!r}")


def render_section(buf: io.StringIO, header: str, values: dict) -> None:
    buf.write(f"[{header}]\n")
    for key, value in values.items():
        if value is None:
            continue
        buf.write(f"{key} = {render_toml_value(value)}\n")
    buf.write("\n")


def render_partition(buf: io.StringIO, partition: dict) -> None:
    buf.write("[[partitions]]\n")
    for key, value in partition.items():
        if value is None:
            continue
        buf.write(f"{key} = {render_toml_value(value)}\n")
    buf.write("\n")


def render_layout_manifest(source_schema_version: int, layout: dict) -> str:
    buf = io.StringIO()
    buf.write("# AUTO-GENERATED by gaia/tools/storage-layout/render_layout_assets.py.\n")
    buf.write(f"# Source: {SOURCE_PATH.relative_to(REPO_ROOT)}\n\n")
    buf.write(f"schema_version = {source_schema_version}\n")
    buf.write(f"layout_id = {render_toml_value(layout['layout_id'])}\n")
    buf.write(f"slot_scheme = {render_toml_value(layout['slot_scheme'])}\n")
    if layout.get("boot_label") is not None:
        buf.write(f"boot_label = {render_toml_value(layout['boot_label'])}\n")
    buf.write("\n")
    render_section(buf, "defaults", layout.get("defaults", {}))
    render_section(buf, "spans", layout.get("spans", {}))
    for partition in layout.get("partitions", []):
        render_partition(buf, partition)
    return buf.getvalue()


def render_layout_env(source_schema_version: int, layout: dict) -> str:
    slot_a = require_partition(layout, "slot_a")
    slot_b = require_partition(layout, "slot_b")
    data = require_partition(layout, "data")
    lines = [
        "# AUTO-GENERATED by gaia/tools/storage-layout/render_layout_assets.py.",
        f"# Source: {SOURCE_PATH.relative_to(REPO_ROOT)}",
        f"HELIOS_LAYOUT_SCHEMA_VERSION={shell_quote(str(source_schema_version))}",
        f"HELIOS_LAYOUT_ID={shell_quote(layout['layout_id'])}",
        f"HELIOS_LAYOUT_SLOT_SCHEME={shell_quote(layout['slot_scheme'])}",
        f"HELIOS_LAYOUT_BOOT_LABEL={shell_quote(str(layout.get('boot_label', '')))}",
        f"HELIOS_LAYOUT_BOOT_PARTITION={shell_quote(str(layout.get('spans', {}).get('boot_partition', '')))}",
        f"HELIOS_LAYOUT_START_AFTER_PARTITION={shell_quote(str(layout.get('spans', {}).get('start_after_partition', '')))}",
        f"HELIOS_LAYOUT_ALIGN_MIB={shell_quote(str(layout.get('defaults', {}).get('align_mib', '')))}",
        f"HELIOS_LAYOUT_GAP_MIB={shell_quote(str(layout.get('defaults', {}).get('gap_mib', '')))}",
        f"HELIOS_LAYOUT_SLOT_A_NAME={shell_quote(slot_a['name'])}",
        f"HELIOS_LAYOUT_SLOT_A_PARTITION={shell_quote(str(slot_a['number']))}",
        f"HELIOS_LAYOUT_SLOT_A_LABEL={shell_quote(str(slot_a.get('label', '')))}",
        f"HELIOS_LAYOUT_SLOT_A_SIZE_SOURCE={shell_quote(str(slot_a.get('size_source', '')))}",
        f"HELIOS_LAYOUT_SLOT_B_NAME={shell_quote(slot_b['name'])}",
        f"HELIOS_LAYOUT_SLOT_B_PARTITION={shell_quote(str(slot_b['number']))}",
        f"HELIOS_LAYOUT_SLOT_B_LABEL={shell_quote(str(slot_b.get('label', '')))}",
        f"HELIOS_LAYOUT_SLOT_B_SIZE_SOURCE={shell_quote(str(slot_b.get('size_source', '')))}",
        f"HELIOS_LAYOUT_SLOT_B_GAP_AFTER_MIB={shell_quote(str(slot_b.get('gap_after_mib', '')))}",
        f"HELIOS_LAYOUT_DATA_NAME={shell_quote(data['name'])}",
        f"HELIOS_LAYOUT_DATA_PARTITION={shell_quote(str(data['number']))}",
        f"HELIOS_LAYOUT_DATA_LABEL={shell_quote(str(data.get('label', '')))}",
        f"HELIOS_LAYOUT_DATA_MARKER={shell_quote(str(data.get('marker', '')))}",
        f"HELIOS_LAYOUT_DATA_SECONDARY_MARKER={shell_quote(str(data.get('secondary_marker', '')))}",
        f"HELIOS_LAYOUT_DATA_MOUNT_POINT={shell_quote(str(data.get('mount_point', '')))}",
    ]
    return "\n".join(lines) + "\n"


def write_or_check(path: pathlib.Path, body: str, check: bool) -> None:
    if check:
        current = path.read_text() if path.exists() else None
        if current != body:
            raise SystemExit(f"generated asset out of date: {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body)


def cmd_generate(check: bool) -> None:
    source = load_source()
    schema_version = int(source["schema_version"])
    for layout in source["layouts"]:
        slug = slugify_layout_id(layout["layout_id"])
        write_or_check(OUTPUT_DIR / f"{slug}.toml", render_layout_manifest(schema_version, layout), check)
        write_or_check(OUTPUT_DIR / f"{slug}.env", render_layout_env(schema_version, layout), check)


def parse_parted_machine_output(raw: str) -> list[dict]:
    partitions: list[dict] = []
    for line in raw.splitlines():
        if not line or not line[0].isdigit():
            continue
        cols = line.split(":")
        if len(cols) < 5:
            continue
        number = int(cols[0])
        start = int(cols[1].rstrip("B"))
        end = int(cols[2].rstrip("B"))
        size = int(cols[3].rstrip("B"))
        fs_type = cols[4].strip()
        partitions.append({"number": number, "start": start, "end": end, "size": size, "fs_type": fs_type})
    return partitions


def partition_fs_magic(path: pathlib.Path, offset: int) -> bytes:
    with path.open("rb") as handle:
        handle.seek(offset)
        return handle.read(4)


def cmd_validate_image(layout_path: pathlib.Path, image_path: pathlib.Path) -> None:
    with layout_path.open("rb") as handle:
        layout = tomllib.load(handle)
    slot_a = require_partition(layout, "slot_a")
    boot_partition = int(layout.get("spans", {}).get("boot_partition", 0))
    slot_a_number = int(slot_a["number"])

    output = subprocess.run(
        ["parted", "-m", "-s", str(image_path), "unit", "B", "print"],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    partitions = parse_parted_machine_output(output.stdout)
    if len(partitions) < 2:
        raise SystemExit(f"{image_path} does not contain enough partitions for layout {layout['layout_id']}")

    by_number = {entry["number"]: entry for entry in partitions}
    if boot_partition not in by_number:
        raise SystemExit(f"{image_path} is missing boot partition {boot_partition}")
    if slot_a_number not in by_number:
        raise SystemExit(f"{image_path} is missing slot-a partition {slot_a_number}")

    boot_entry = by_number[boot_partition]
    slot_entry = by_number[slot_a_number]
    if not boot_entry["fs_type"].lower().startswith("fat"):
        raise SystemExit(f"{image_path} boot partition {boot_partition} is not FAT")

    scheme = layout["slot_scheme"]
    if scheme == "ext4_labels":
        if slot_entry["fs_type"] not in {"ext2", "ext3", "ext4"}:
            raise SystemExit(f"{image_path} slot-a partition {slot_a_number} is not ext4-like")
    elif scheme == "squashfs_ab":
        magic = partition_fs_magic(image_path, slot_entry["start"])
        if magic != b"hsqs":
            raise SystemExit(f"{image_path} slot-a partition {slot_a_number} is not squashfs")
    else:
        raise SystemExit(f"unsupported slot scheme {scheme}")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)

    generate = subparsers.add_parser("generate")
    generate.add_argument("--check", action="store_true")

    validate_image = subparsers.add_parser("validate-image")
    validate_image.add_argument("--layout", type=pathlib.Path, required=True)
    validate_image.add_argument("--image", type=pathlib.Path, required=True)

    args = parser.parse_args(argv)
    if args.command == "generate":
        cmd_generate(check=args.check)
    elif args.command == "validate-image":
        cmd_validate_image(args.layout, args.image)
    else:
        parser.error(f"unsupported command {args.command}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
