[rust]
enabled = true
workspace_dir = "../backend"
check_ids = []

[[rust.artifacts]]
id = "helios-api"
package = "helios-api"
kind = "bin"
profile = "aarch64-linux"
mode = "auto"
build_command = ["cargo", "build", "-p", "helios-api", "--bin", "helios-api", "--release", "--target", "aarch64-unknown-linux-gnu"]
output_path = "../.gaia-target/aarch64-linux/aarch64-unknown-linux-gnu/release/helios-api"

[[rust.artifacts]]
id = "helios-diagnostics"
package = "helios-diagnostics"
kind = "bin"
profile = "aarch64-linux"
mode = "auto"

[[rust.artifacts]]
id = "orion-node"
package = "orion-node"
bin = "orion-node"
kind = "bin"
profile = "aarch64-linux"
mode = "auto"
source = { kind = "git", repo = "https://github.com/Prometheus-Dynamics/Orion.git", ref = "main" }

[rust.artifacts.cargo.profile]
lto = "fat"
codegen_units = 1
opt_level = "z"
strip = "symbols"

[[rust.artifacts]]
id = "helios-engine"
package = "helios-engine"
kind = "bin"
profile = "aarch64-linux"
mode = "auto"

[[rust.artifacts]]
id = "helios-updater"
package = "helios-updater"
kind = "bin"
profile = "aarch64-linux"
mode = "auto"

[[rust.artifacts]]
id = "helios-peripherals"
package = "helios-peripherals"
kind = "bin"
profile = "aarch64-linux"
mode = "auto"

[[rust.artifacts]]
id = "helios-provision"
package = "helios-provision"
kind = "bin"
profile = "aarch64-linux"
mode = "auto"
