[package]
name = "lib-net"
version.workspace = true
edition = "2024"

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
tokio = {workspace = true}
futures = {workspace = true}
tracing = {workspace = true}
default-net = "0.22.0"
rtnetlink = "0.20.0"
netlink-packet-route = "0.29.0"
hostname = {version = "0.4.2", features = ["set"]}
thiserror = {workspace = true}
serde = {workspace = true}
get_if_addrs = "0.5.3"
mdns-sd = "0.18.2"
utoipa = { workspace = true }
async-trait = { workspace = true }
libc = { workspace = true }
nix = { version = "0.31.2", default-features = false, features = ["signal", "process"] }

[dev-dependencies]
tempfile = "3.27"
