[package]
name = "lib-net"
version.workspace = true
edition = "2024"

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
tokio = {workspace = true}
futures = {workspace = true}
tracing = {workspace = true}
default-net = { workspace = true }
rtnetlink = { workspace = true }
netlink-packet-route = { workspace = true }
hostname = { workspace = true }
thiserror = {workspace = true}
serde = {workspace = true}
get_if_addrs = { workspace = true }
mdns-sd = { workspace = true }
utoipa = { workspace = true }
async-trait = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
