[package]
name = "lib-math"
version.workspace = true
edition = "2024"

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
rand = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
quickcheck = "1.1.0"
quickcheck_macros = "1.2.0"
criterion = "0.8.2"
