server.document-root = "/opt/helios/frontend"
server.bind = "0.0.0.0"
server.port = 5800
server.max-fds = 2048
server.errorlog = "/var/log/helios/frontend/error.log"
accesslog.filename = "/var/log/helios/frontend/access.log"

server.modules = (
  "mod_access",
  "mod_accesslog",
  "mod_alias",
  "mod_redirect",
  "mod_indexfile",
  "mod_staticfile",
  "mod_proxy"
)

index-file.names = ( "index.html" )

$HTTP["url"] !~ "^/docs/" {
  server.error-handler-404 = "/index.html"
}

proxy.stream-response-body = 2
server.stream-response-body = 2

$HTTP["url"] =~ "^/v1" {
  proxy.server = ( "" => ( ( "host" => "127.0.0.1", "port" => 5801 ) ) )
  proxy.header = ( "upgrade" => "enable" )
}

mimetype.assign = (
  ".html" => "text/html",
  ".css"  => "text/css",
  ".js"   => "application/javascript",
  ".json" => "application/json",
  ".wasm" => "application/wasm",
  ".svg"  => "image/svg+xml",
  ".png"  => "image/png",
  ".jpg"  => "image/jpeg",
  ".jpeg" => "image/jpeg",
  ".ico"  => "image/x-icon",
)
