[package]
name = "lib-nt4-macro"
version.workspace = true
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
lib-asyncapi = { path = "../lib-asyncapi" }
lib-asyncapi-macro = { path = "../lib-asyncapi-macro" }
futures.workspace = true

[dev-dependencies]
lib-nt4 = { path = "../lib-nt4" }
serde_json = { workspace = true }
nt_client = { workspace = true }
