// Generated by tools/api-codegen/generate-runtime-contracts.mjs. Do not edit by hand.

pub mod stream_ids {
    use uuid::Uuid;

    pub const RAW_PIPELINE_UUID: Uuid = uuid::uuid!("00000000-0000-0000-0000-0000000000aa");
    pub const LEGACY_RAW_PIPELINE_UUID: Uuid = uuid::uuid!("00000000-0000-0000-0000-0000000000ab");
    pub const CALIBRATION_MODE_PIPELINE_UUID: Uuid = uuid::uuid!("00000000-0000-0000-0000-00000000c411");
}

pub mod localization {
    pub const DEVICE_IMU_EXTERNAL_SOURCE_ID: &str = "imu";
}
