// Generated by backend/tools/xtask from tools/api-codegen/runtime-contracts.toml. Do not edit by hand.
// reserved_pipeline_ids owner: HeliOS | boundary: helios-engine <-> frontend reserved runtime pipeline ids | source_of_truth: backend/src/helios-engine/src/contracts.rs
// localization_external_source_ids owner: HeliOS | boundary: helios-api <-> frontend localization external source ids | source_of_truth: frontend/src/lib/features/localization/externalSourceIds.ts

pub mod stream_ids {
    use uuid::Uuid;

    pub const CALIBRATION_MODE_PIPELINE_UUID: Uuid = uuid::uuid!("00000000-0000-0000-0000-00000000c411");
    pub const LEGACY_RAW_PIPELINE_UUID: Uuid = uuid::uuid!("00000000-0000-0000-0000-0000000000ab");
    pub const RAW_PIPELINE_UUID: Uuid = uuid::uuid!("00000000-0000-0000-0000-0000000000aa");
}

pub mod localization {
    pub const DEVICE_IMU_EXTERNAL_SOURCE_ID: &str = "imu";
}
