[package]
name = "lib-nt4"
version.workspace = true
edition = "2021"

[dependencies]
tokio.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing.workspace = true
futures.workspace = true
lib-asyncapi = { path = "../lib-asyncapi" }
lib-transport = { path = "../lib-transport" }
nt_client.workspace = true
rmpv.workspace = true
url.workspace = true
schemars.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time"] }
lib-nt4-macro = { path = "../lib-nt4-macro" }
serde_json.workspace = true
lib-asyncapi-macro = { path = "../lib-asyncapi-macro" }

[dependencies.lib-nt4-macro]
path = "../lib-nt4-macro"
optional = true

[features]
macros = ["lib-nt4-macro"]
