[package]
name = "helios-provision"
version = "0.1.1"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
lib-storage-layout = { path = "../../src/libs/lib-storage-layout" }
serde = { workspace = true, features = ["derive"] }
toml = "1.0.6"
thiserror = { workspace = true }
