// Generated by backend/tools/xtask from tools/api-codegen/codec-families.toml. Do not edit by hand.
// owner: Shared HeliOS/Styx | boundary: helios-api/engine <-> frontend stream encoder family ids | source_of_truth: tools/api-codegen/codec-families.toml

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub(super) enum GeneratedEncoderFamilyVariant {
    Turbojpeg,
    Mozjpeg,
    FfmpegMjpeg,
    H264,
    H265,
}

#[derive(Debug, Clone, Copy)]
pub(super) struct GeneratedEncoderFamilySpec {
    pub variant: GeneratedEncoderFamilyVariant,
    pub selector_id: &'static str,
    pub selector_aliases: &'static [&'static str],
    pub runtime_implementation_aliases: &'static [&'static str],
    pub runtime_name_aliases: &'static [&'static str],
    pub output_fourcc_aliases: &'static [&'static str],
    pub recording_codec: Option<&'static str>,
}

pub(super) const ENCODER_SELECTOR_ID_TURBOJPEG: &str = "turbojpeg";
pub(super) const ENCODER_SELECTOR_ID_MOZJPEG: &str = "mozjpeg";
pub(super) const ENCODER_SELECTOR_ID_FFMPEG_MJPEG: &str = "mjpeg";
pub(super) const ENCODER_SELECTOR_ID_H264: &str = "h264";
pub(super) const ENCODER_SELECTOR_ID_H265: &str = "h265";

pub(super) const GENERATED_ENCODER_FAMILY_SPECS: &[GeneratedEncoderFamilySpec] = &[
    GeneratedEncoderFamilySpec {
        variant: GeneratedEncoderFamilyVariant::Turbojpeg,
        selector_id: ENCODER_SELECTOR_ID_TURBOJPEG,
        selector_aliases: &["turbojpeg"],
        runtime_implementation_aliases: &["turbojpeg"],
        runtime_name_aliases: &[],
        output_fourcc_aliases: &["MJPG", "JPEG"],
        recording_codec: None,
    },
    GeneratedEncoderFamilySpec {
        variant: GeneratedEncoderFamilyVariant::Mozjpeg,
        selector_id: ENCODER_SELECTOR_ID_MOZJPEG,
        selector_aliases: &["mozjpeg"],
        runtime_implementation_aliases: &["mozjpeg"],
        runtime_name_aliases: &[],
        output_fourcc_aliases: &["MJPG", "JPEG"],
        recording_codec: None,
    },
    GeneratedEncoderFamilySpec {
        variant: GeneratedEncoderFamilyVariant::FfmpegMjpeg,
        selector_id: ENCODER_SELECTOR_ID_FFMPEG_MJPEG,
        selector_aliases: &["mjpeg", "mjpg", "jpeg"],
        runtime_implementation_aliases: &["ffmpeg"],
        runtime_name_aliases: &["mjpeg"],
        output_fourcc_aliases: &["MJPG", "JPEG"],
        recording_codec: None,
    },
    GeneratedEncoderFamilySpec {
        variant: GeneratedEncoderFamilyVariant::H264,
        selector_id: ENCODER_SELECTOR_ID_H264,
        selector_aliases: &["h264", "avc"],
        runtime_implementation_aliases: &["ffmpeg", "h264_v4l2m2m"],
        runtime_name_aliases: &["h264", "avc"],
        output_fourcc_aliases: &["H264"],
        recording_codec: Some("h264"),
    },
    GeneratedEncoderFamilySpec {
        variant: GeneratedEncoderFamilyVariant::H265,
        selector_id: ENCODER_SELECTOR_ID_H265,
        selector_aliases: &["h265", "hevc"],
        runtime_implementation_aliases: &["ffmpeg", "hevc_v4l2m2m", "h265_v4l2m2m"],
        runtime_name_aliases: &["h265", "hevc"],
        output_fourcc_aliases: &["H265", "HEVC"],
        recording_codec: Some("h265"),
    }
];
