#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
SOURCE_PATH = REPO_ROOT / "gaia/configs/env/runtime/runtime-policy-source.toml"
ENV_OUTPUT_PATH = REPO_ROOT / "gaia/configs/env/runtime/generated-runtime-policy.toml"
RUST_OUTPUT_PATH = REPO_ROOT / "backend/src/libs/lib-runtime-policy/src/generated.rs"
TOKIO_FIELDS = ("worker_threads", "max_blocking_threads", "thread_stack_bytes", "blocking_keep_alive_ms")


def load_source() -> dict:
    return tomllib.loads(SOURCE_PATH.read_text(encoding="utf-8"))


def render_env_toml(source: dict) -> str:
    profiles = source["profiles"]
    services = source["services"]
    lines = [
        "# This file is generated by gaia/tools/runtime-policy/render_runtime_policy.py.",
        f"# Source: {SOURCE_PATH.relative_to(REPO_ROOT)}",
        "",
    ]

    for service_name, service in services.items():
        env = {}
        for profile_name in service.get("profiles", []):
            env.update(profiles[profile_name])
        env.update(service.get("env", {}))
        tokio_policy = service.get("tokio", {})
        for field_name in TOKIO_FIELDS:
            field = tokio_policy.get(field_name)
            if field is not None:
                env[field["env"]] = str(field["default"])

        lines.append(f'[sets.{service_name}]')
        for key in sorted(env):
            lines.append(f'{key} = "{env[key]}"')
        lines.append("")

    return "\n".join(lines)


def render_rust(source: dict) -> str:
    services = source["services"]
    lines = [
        "// This file is generated by gaia/tools/runtime-policy/render_runtime_policy.py.",
        f"// Source: {SOURCE_PATH.relative_to(REPO_ROOT)}",
        "",
        "use crate::{BoundedU64Policy, BoundedUsizePolicy, TokioRuntimePolicy};",
        "",
    ]

    for service_name, service in services.items():
        tokio_policy = service.get("tokio")
        if tokio_policy is None:
            continue

        const_name = service_name.upper().replace("-", "_") + "_TOKIO_POLICY"
        lines.append(f"pub const {const_name}: TokioRuntimePolicy = TokioRuntimePolicy {{")
        for field_name in ("worker_threads", "max_blocking_threads"):
            field = tokio_policy[field_name]
            lines.append(f"    {field_name}: BoundedUsizePolicy {{ env_var: \"{field['env']}\", default: {field['default']}, min: {field['min']}, max: {field['max']} }},")
        for field_name, policy_type in (("thread_stack_bytes", "BoundedUsizePolicy"), ("blocking_keep_alive_ms", "BoundedU64Policy")):
            field = tokio_policy.get(field_name)
            if field is None:
                lines.append(f"    {field_name}: None,")
            else:
                lines.append(
                    "    "
                    + field_name
                    + f": Some({policy_type} {{ env_var: \"{field['env']}\", default: {field['default']}, min: {field['min']}, max: {field['max']} }}),"
                )
        lines.append("};")
        lines.append("")

    return "\n".join(lines)


def write_output(path: Path, contents: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents, encoding="utf-8")


def output_matches(path: Path, expected: str) -> bool:
    return path.exists() and path.read_text(encoding="utf-8") == expected


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render shared runtime policy outputs.")
    subparsers = parser.add_subparsers(dest="command", required=True)
    generate = subparsers.add_parser("generate", help="Write or verify generated runtime policy files.")
    generate.add_argument("--check", action="store_true", help="Fail if generated outputs are out of date.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    source = load_source()
    env_output = render_env_toml(source)
    rust_output = render_rust(source)

    if args.check:
        stale = []
        if not output_matches(ENV_OUTPUT_PATH, env_output):
            stale.append(ENV_OUTPUT_PATH)
        if not output_matches(RUST_OUTPUT_PATH, rust_output):
            stale.append(RUST_OUTPUT_PATH)
        if stale:
            for path in stale:
                print(f"runtime policy output is stale: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            return 1
        print("Runtime policy outputs are up to date.")
        return 0

    write_output(ENV_OUTPUT_PATH, env_output)
    write_output(RUST_OUTPUT_PATH, rust_output)
    print(
        "Rendered runtime policy outputs: "
        f"{ENV_OUTPUT_PATH.relative_to(REPO_ROOT)}, {RUST_OUTPUT_PATH.relative_to(REPO_ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
