[package]
name = "lib-cv"
version.workspace = true
edition = "2024"

[lib]
doctest = false

[lints]
workspace = true

[features]
default = []
all = ["contour", "draw", "aruco"]
contour = []
draw = []
aruco = []
engine = ["dep:daedalus", "dep:daedalus-data", "dep:daedalus-macros", "dep:paste", "daedalus/engine", "daedalus/plugins"]
plugins = ["engine"]
gpu = ["engine", "daedalus/gpu-wgpu"]

[dependencies]
tokio = {workspace = true}
tracing = {workspace = true}
rayon = {workspace = true}
ffmpeg = {workspace = true}
async-trait = {workspace = true}
serde = {workspace = true}
utoipa = {workspace = true}
uuid = {workspace = true}
daedalus = { workspace = true, features = ["engine", "plugins", "gpu"], optional = true }
daedalus-data = { workspace = true, optional = true }
daedalus-macros = { workspace = true, optional = true }

num = { workspace = true }
ab_glyph = { workspace = true }
serde_json = {workspace = true}
bytemuck = { workspace = true }
wide = { workspace = true }
geo = { workspace = true }
nalgebra = { workspace = true }
rand = { workspace = true }
once_cell = { workspace = true }
serde_bytes = { workspace = true }
paste = { workspace = true, optional = true }
memchr = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
