[package]
name = "lib-cv"
version.workspace = true
edition = "2024"

[lib]
doctest = false

[lints]
workspace = true

[features]
default = ["all", "plugins"]
all = ["contour", "ai", "draw", "aruco"]
contour = []
ai = []
draw = []
aruco = []
engine = ["dep:daedalus", "dep:daedalus-data", "dep:daedalus-macros", "dep:paste", "daedalus/engine", "daedalus/plugins"]
plugins = ["engine"]
gpu = ["engine", "dep:wgpu", "daedalus/gpu-wgpu"]

[dependencies]
tokio = {workspace = true}
tracing = {workspace = true}
image = {workspace = true}
imageproc = {workspace = true}
rayon = {workspace = true}
ffmpeg = {workspace = true}
async-trait = {workspace = true}
serde = {workspace = true}
utoipa = {workspace = true}
uuid = {workspace = true}
daedalus = { workspace = true, features = ["engine", "plugins", "gpu"], optional = true }
daedalus-data = { workspace = true, optional = true }
daedalus-macros = { workspace = true, optional = true }

fast_image_resize = { version = "6.0.0", features = ["image", "rayon"] }
libblur = { version = "0.23.1", features = ["image"] }
num = "0.4.3"
ab_glyph = "0.2.32"
serde_json = {workspace = true}
bytemuck = "1.25.0"
wide = "1.1.1"
geo = { workspace = true }
nalgebra = "0.34.1"
rand = { workspace = true }
once_cell = { workspace = true }
serde_bytes = { workspace = true }
paste = { workspace = true, optional = true }
wgpu = { version = "28.0.0", default-features = false, features = ["wgsl"], optional = true }
memchr = "2.8.0"
smallvec = "1.15.1"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }


[build-dependencies]
naga = { version = "28.0", features = ["wgsl-in"] }
