[package]
name = "lib-ai"
version.workspace = true
edition = "2024"

[features]
default = ["backend-cpu"]

api = []
schema = ["dep:utoipa"]

engine = ["api", "dep:image", "dep:paste", "dep:daedalus", "daedalus/engine", "daedalus/plugins"]
plugins = ["engine"]
backend-cpu = ["backend-tflite", "backend-onnx"]
backend-tflite = ["dep:tract-tflite", "dep:tract-core"]
backend-onnx = ["dep:tract-onnx", "dep:tract-core"]
backend-coral = ["dep:rusb", "dep:tract-tflite", "dep:tract-core", "dep:libc"]
docs = []

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
uuid = { workspace = true }
lib-schema-migration = { path = "../lib-schema-migration" }
libloading = { version = "0.9.0" }
serde_json = { workspace = true }
image = { workspace = true, optional = true }
imageproc = { workspace = true }
ab_glyph = "0.2.32"
lib-cv = { path = "../lib-cv", default-features = false }
tracing = { workspace = true }
rayon = { workspace = true }
bytemuck = { workspace = true }
daedalus = { workspace = true, features = ["engine", "plugins"], optional = true }
paste = { workspace = true, optional = true }
utoipa = { workspace = true, optional = true }

tract-core = { version = "0.22.1", optional = true }
tract-tflite = { version = "0.22.1", optional = true }
tract-onnx = { version = "0.22.1", optional = true }
rusb = { version = "0.9.4", optional = true }
tokio = { workspace = true }
libc = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }
tempfile = "3.27.0"
