[package]
name = "heliosctl"
version.workspace = true
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
hex = { workspace = true }
orion = { workspace = true, default-features = false, features = ["client", "control-plane", "core"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
helios-diagnostics = { path = "../diagnostics" }
