[package]
name = "heliosctl"
version.workspace = true
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true }
serde_json = { workspace = true }
helios-diagnostics = { path = "../diagnostics" }

[dev-dependencies]
tempfile = { workspace = true }
