[package]
name = "helios-peripherals"
version.workspace = true
edition = "2024"

[features]
default = ["runtime"]
dto = [
    "serde",
    "serde_json",
    "uuid",
    "lib-ipc",
    "derive_more",
    "bincode",
    "lib-ai",
    "lib-sensors",
]
runtime = [
    "dto",
    "tokio",
    "tokio-util",
    "futures",
    "tracing",
    "tracing-subscriber",
    "clap",
    "chrono",
    "bincode",
    "serde_json",
    "nix",
    "lib-ai",
    "lib-sensors",
    "lib-math",
    "linux-embedded-hal",
    "toml",
]
schema = ["dto", "dep:utoipa"]

[[bin]]
name = "helios-peripherals"
path = "src/main.rs"
required-features = ["runtime"]

[lib]
name = "helios_peripherals"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"], optional = true }
uuid = { workspace = true, optional = true }
lib-ipc = { path = "../libs/lib-ipc", optional = true }
derive_more = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
bincode = { workspace = true, features = ["serde"], optional = true }
lib-ai = { path = "../libs/lib-ai", default-features = false, features = ["engine", "backend-coral", "backend-tflite"], optional = true }
serde_json = { workspace = true, optional = true }
nix = { version = "0.28", features = ["fs"], optional = true }
lib-sensors = { path = "../libs/lib-sensors", optional = true }
lib-math = { path = "../libs/lib-math", optional = true }
linux-embedded-hal = { workspace = true, optional = true }
toml = { version = "0.8", optional = true }
utoipa = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }
